### PR TITLE
Add XDebug

### PR DESCRIPTION
**Pull request by PineappleIOnic**
## What does this PR do?

This PR adds XDebug version 8.2.2

### CODE REVIEW

**Comment by eldadfux** [comment]
@PineappleIOnic I am pretty sure this will cause the entire server to be slower if always enabled. Please double check

**Comment by PineappleIOnic** [comment]
It isn't always enabled, we never add the extension to the ini files. My second PR within Appwrite does that under the `DEBUG` flag

**Comment by eldadfux** [comment]
Got it, do we have some way to test this addition under the existing tests?

**Comment by PineappleIOnic** [comment]
I'm not entirely sure what exactly to test here sorry, we could have checks that validate that xdebug_info() exists if DEBUG=true or something like that if that's what your thinking of

**Review by abnegate — APPROVED** [review]

**Pull request merged**
