### PR TITLE
Feat: Support for CURL in Swoole

### PR DESCRIPTION
**Pull request by Meldiron**
## What does this PR do?

Adds async support to `curl()`

## Test Plan

Manual QA with log streaming in Appwrite

## Related PRs and Issues

x
### Have you read the [Contributing Guidelines on issues](https://github.com/appwrite/appwrite/blob/master/CONTRIBUTING.md)?

Yes

### CODE REVIEW

**Comment by eldadfux** [comment]
@Meldiron do we still need this or can we close this PR?

**Comment by Meldiron** [comment]
Doesnt seem to be nessessary anymore.

**Comment by Meldiron** [comment]
seems relevant. We are facing some CURL bugs that are most likely related to these changes

**Comment by Meldiron** [comment]
Closing in favour of https://github.com/appwrite/docker-base/pull/17

**Pull request closed without merging**
